
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beiximbpoiiuqnkjrnou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaXhpbWJwb2lpdXFua2pybm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODk1NjMsImV4cCI6MjA2MDQ2NTU2M30.cAwb1NIXPkTpfV0bVrNL4vn9Kg2FznnFX8Q74K_kLl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
